[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/pastel_dark.toml"
]

[font]
normal = {family = "MesloLGS Nerd Font Mono", style = "Regular"}
bold = {family = "MesloLGS Nerd Font Mono", style = "Bold"}
italic = {family = "MesloLGS Nerd Font Mono", style = "Italic"}

[window.dimensions]
columns = 133
lines = 30
